/*
 * Demo Server
 *
 * This is the API descriptor for demo server
 *
 * API version: 1.0.0
 * Contact: bensong2017@hotmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// BatchOperateCypher - cypher
func BatchOperateCypher(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
