/*
 * Demo Server
 *
 * This is the API descriptor for demo server
 *
 * API version: 1.0.0
 * Contact: bensong2017@hotmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

type Cypher struct {

	// Platform store ID
	StoreId string `json:"storeId"`

	// Platform name
	Platform string `json:"platform"`

	Operation CypherOperation `json:"operation"`

	Items []string `json:"items,omitempty"`
}
