/*
 * Demo Server
 *
 * This is the API descriptor for demo server
 *
 * API version: 1.0.0
 * Contact: bensong2017@hotmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

type ApiResponse struct {

	Code int32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	Data ApiResponseData `json:"data,omitempty"`
}
