/*
 * Demo Server
 *
 * This is the API descriptor for demo server
 *
 * API version: 1.0.0
 * Contact: bensong2017@hotmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver
// CypherOperation : operation name, AreAllEncrypted, EncryptBatch and DecryptBatch
type CypherOperation string

// List of CypherOperation
const (
	ARE_ALL_ENCRYPTED CypherOperation = "AreAllEncrypted"
	ENCRYPT_BATCH CypherOperation = "EncryptBatch"
	DECRYPT_BATCH CypherOperation = "DecryptBatch"
)
